# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3233b043cc0986546f1e1d75d9c8d94147532da10db4c0721ff9212084abaf63bcb6c9df006f65b88886d1ff7222c25bea6308e6bd0079ebef26fa94cd0200a

test:
  secret_key_base: 8a93bdc2431d66e14aa01e68650f095ce2b40196505c42f0a288a77f03d43a01325563f05350e59257819508dddaa2eaca910f691b1ac4d3956177f83a506393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
